[tools]
erlang = "26.2.5.1"
elixir = "1.19.4-otp-26"

[vars]
certs_path = "priv/certs"

[env]
KERL_BUILD_DOCS = "yes"
ERL_AFLAGS = "-kernel shell_history enabled"
TEI_TLS_PRIVATE_KEY_PATH = "{{vars.certs_path}}/localhost.key"
TEI_TLS_CERT_PATH = "{{vars.certs_path}}/localhost.crt"
TEI_TLS_CA_CERT_PATH = "{{vars.certs_path}}/localhost.crt"
TEI_TLS_DH_FILE_PATH = "{{vars.certs_path}}/dh-params.pem"
PGPASSWORD = "123456789"
TEI_ENABLE_EMAIL_INTEGRATION = "true"
TEI_SMTP_SERVER = "127.0.0.1"
TEI_SMTP_HOSTNAME = "localhost"
TEI_SMTP_USERNAME = ""
TEI_SMTP_PASSWORD = ""
TEI_SMTP_PORT = "1025"
TEI_SMTP_TLS = "never"
TEI_SMTP_TLS_VERIFY = "false"
TEI_SMTP_AUTH = "never"

[tasks."setup:db"]
description = "Sets up the application database"
run = "mix do ecto.drop + ecto.setup"

[tasks."setup:deps"]
run = "mix deps.get"

[tasks."setup:tachyon"]
description = "On demand task that sets up the tachyon ouath application that allows the new bar lobby to connect"
run = "mix teiserver.tachyon_setup"

[tasks."setup:fakedata"]
description = "On demand task that sets up fake data for testing"
run = "mix teiserver.fakedata"

[tasks.setup]
depends = ["setup:deps"]
description = "Sets up the application dependencies from scratch"
run = [{ task = "setup:certs:*" }, { tasks = ["setup:sass", "setup:db"] }]

[tasks."setup:sass"]
run = "mix sass.install"

[tasks."setup:certs:dhparam"]
sources = ["mise.toml"]
outputs = ["{{env.TEI_TLS_DH_FILE_PATH}}"]
run = "openssl dhparam -out {{env.TEI_TLS_DH_FILE_PATH}} 2048"

[tasks."setup:certs:cert"]
shell = "bash -c"
sources = ["mise.toml"]
outputs = ["{{env.TEI_TLS_CERT_PATH}}", "{{env.TEI_TLS_PRIVATE_KEY_PATH}}"]
env.CERT_SSL_CONFIG = '''
[dn]
CN=localhost
[req]
distinguished_name = dn
[EXT]
subjectAltName=DNS:localhost
keyUsage=digitalSignature
extendedKeyUsage=serverAuth
'''
run = '''
openssl req -x509 \
  -out {{env.TEI_TLS_CERT_PATH}} \
  -keyout {{env.TEI_TLS_PRIVATE_KEY_PATH}} \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT \
  -config <(printf "${CERT_SSL_CONFIG}")
'''

[tasks.tests]
description = "Run tests, except those tagged with `:needs_attention`"
run = "mix test --exclude needs_attention"
alias = "t"

[tasks.server]
description = "Start the Phoenix application with debugging enabled" # https://hexdocs.pm/elixir/debugging.html#pry
run = "iex --dbg pry -S mix phx.server"
alias = "s"
