use Mix.Config

config :central, Central.Setup, key: "dev_key"

# Configure your database
config :central, Central.Repo,
  username: "postgres",
  password: "postgres",
  database: "teiserver_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :central, CentralWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]


config :central, Teiserver,
  certs: [
    keyfile: "priv/certs/localhost.key",
    certfile: "priv/certs/localhost.crt",
    cacertfile: "priv/certs/localhost.crt"
  ],
  ports: [
    tcp: 8200,
    tls: 8201
  ],
  heartbeat_interval: nil,
  heartbeat_timeout: nil,
  autologin: true,
  extra_logging: false,
  enable_discord_bridge: false,
  enable_agent_mode: true,
  use_geoip: true

config :central, Central.Mailer,
  adapter: Bamboo.LocalAdapter,
  noreply_address: "noreply@devsite.co.uk",
  contact_address: "info@devsite.co.uk"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :central, CentralWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/central_web/views/.*(ex)$},
      ~r{lib/central_web/templates/.*(eex)$},
      ~r{lib/teiserver_web/views/.*(ex)$},
      ~r{lib/teiserver_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :central, Central.Communication.BlogFile, save_path: "/tmp/blog_files"

config :logger,
  format: "[$level] $message\n",
  backends: [
    {LoggerFileBackend, :error_log},
    {LoggerFileBackend, :info_log},
    :console
  ]

# Comment the below block to stop background jobs happening in dev
# config :central, Oban,
#   queues: false,
#   crontab: false

config :logger, :error_log,
  path: "/tmp/barserver_error.log",
  level: :error

config :logger, :info_log,
  path: "/tmp/barserver_info.log",
  level: :info

try do
  import_config "dev.secret.exs"
rescue
  _ ->
    nil
end
