name: build prod container image and push to registry

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build prod container
    permissions:
      packages: write
      contents: read
    env:
      REGISTRY: ghcr.io
      IMAGE: ghcr.io/${{ github.repository }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to registry
      run: buildah login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} $REGISTRY

    - name: Build latest image
      run: |
        buildah bud -t $IMAGE:latest .
        buildah push $IMAGE:latest

    - name: Build tagged image
      if: github.event_name == 'release'
      run: |
        buildah bud -t $IMAGE:${{ github.event.release.tag_name }} .
        buildah push $IMAGE:${{ github.event.release.tag_name }}